services:
  - type: web
    name: keycloak
    runtime: docker
    dockerfilePath: ./keycloak/Dockerfile
    dockerContext: ./keycloak
    envVars:
      - key: KC_DB
        value: postgres
      - key: KC_DB_URL
        value: jdbc:postgresql://dpg-d46tda6r433s738eq500-a.singapore-postgres.render.com/keycloak_o71s
      - key: KC_DB_USERNAME
        value: keycloak
      - key: KC_DB_PASSWORD
        value: 0o8bg1cxvPx8rgi8A7I13ZeA5kUGuNT6
      - key: KC_HOSTNAME
        value: keycloak-bqji.onrender.com
      - key: KC_PROXY
        value: edge
      - key: KC_HTTP_PORT
        value: 10000
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: AdminPassword123
